export const ActionType = {
  SET_CREDIT_DATA: 'SET_CREDIT_DATA',
  CHANGE_PURPOSE: 'CHANGE_PURPOSE',
  CHANGE_COST: 'CHANGE_COST',
  CHANGE_INITIAL_FEE: 'CHANGE_INITIAL_FEE',
  CHANGE_FIELD_VALUE: 'CHANGE_FIELD_VALUE',
  CHANGE_ADDITIONAL: 'CHANGE_ADDITIONAL',
};
